### PR TITLE
DOC-6576-Update Sync Gateway Kubernetes Deployment Docs to align with…

### PR DESCRIPTION
**Pull request by ibsoln**
… updated Operator 2.0.0 tutorials

https://issues.couchbase.com/browse/DOC-6576

https://ibsoln.github.io/stage/DOC-6576-2/operator/2.0/tutorial-sync-gateway-manage.html

### CODE REVIEW

**Comment by ibsoln** [comment]
@rajagp review ready

Ticket: https://issues.couchbase.com/browse/DOC-6576
PR: https://github.com/couchbase/docs-sync-gateway/pull/222
Staged: https://ibsoln.github.io/stage/DOC-6576-2/sync-gateway/2.7/kubernetes/deploy-cluster.html

**Comment by rajagp** [comment]
@ibsoln  Not sure where this is specified (I couldn't see it in PR) but please change

> Provides access to instruction on deploying a Sync Gateway cluster on Kubernetes and connecting with a Couchbase Server instance

to

Provides access to instruction on deploying a Sync Gateway cluster on Kubernetes and connecting with a Couchbase Server cluster

**Review by rajagp — APPROVED** [review]
@ibsoln Not sure where this is specified (I couldn't see it in PR) but please change

> Summary: Provides access to instruction on deploying a Sync Gateway cluster on Kubernetes and connecting with a Couchbase Server instance

to

Provides access to instruction on deploying a Sync Gateway cluster on Kubernetes and connecting with a Couchbase Server cluster

Otherwise looks good.

**Comment by ibsoln** [comment]
> @ibsoln Not sure where this is specified (I couldn't see it in PR) but please change
> 
> > Summary: Provides access to instruction on deploying a Sync Gateway cluster on Kubernetes and connecting with a Couchbase Server instance
> 
> to
> 
> Provides access to instruction on deploying a Sync Gateway cluster on Kubernetes and connecting with a Couchbase Server cluster
> 
> Otherwise looks good.

Cheers @rajagp -- amended in a419c224cd480236cae1b6f44231d60c1b1cd2c9 and merged

**Pull request merged**
