### PR TITLE
CBG-2792 - Relnotes SGW 3.0.6

### PR DESCRIPTION
**Pull request by osfameron**
https://docs-staging.couchbase.com/sync-gateway/current/release-notes.html#maint-3-0-6

### CODE REVIEW

**Review by franrob-projects — COMMENTED** [review]
💯

**Review by franrob-projects — APPROVED** [review]

**Review by dinaabennett — APPROVED** [review]

**Comment by franrob-projects** [comment]
@dinaabennett can you give my (Jira link) adjustments a quick sanity check, please?

**Review by franrob-projects — APPROVED** [review]

**Review by dinaabennett — APPROVED** [review]
:-)

**Review by bfavini — APPROVED** [review]
Looks good to me

**Pull request merged**
