### PR TITLE
DOC-5872 - update getting started

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-5872

[Getting Started](https://ibsoln.github.io/DOC-5872/sync-gateway/2.6/getting-started.html)

Changes:

- Update screenshots for 6.0
- Update text instructions to create a bucket called `getting-started-bucket`
- Add a step for the bucket creation pop-up
- Link to 'Configure Sync Gateway' from 'Creating an RBAC user'

### CODE REVIEW

**Review by rajagp — COMMENTED** [review]
@jamiltz  Note that I was not able to view any of the images as part of review. So not sure what is being proposed.  I trust that the screenshots and steps are for the latest version couchbase server. If there is a staged version of this page, I can review

**Comment by jamesnocentini** [comment]
@rajagp , Yes, GitHub PRs don't render them by default. But you can click the rich diff icon 
image

**Comment by jamesnocentini** [comment]
@rajagp Staged version is possible. There is a process on docs server to use personal github pages  to host it ([example](https://github.com/couchbase/docs-server/pull/896)). I'll provide that.

**Comment by jamesnocentini** [comment]
@rajagp we've updated the first comment on the PR with a staging link. For your information, it's a partial build and only contains sync-gateway and cbl components. So links to server docs will be broken on this staging site but will otherwise work in production. I've requested a re-review.

**Review by ibsoln — APPROVED** [review]

**Pull request merged**
