### PR TITLE
DOC-5216

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-5216

### CODE REVIEW

**Review by RichardSmedley — APPROVED** [review]
I'm not an SME for this API, but LGTM

**Comment by simon-dew** [comment]
The JSON looks incorrect to me

**Comment by simon-dew** [comment]
I think there should be a comma after the `}` on line 42

**Comment by simon-dew** [comment]
Delete the comma after the `}` on line 85 (using the new line numbers after your edits)

**Review by simon-dew — CHANGES_REQUESTED** [review]
Errors in JSON file outside of the additional lines in this edit. See my other comments.

**Comment by RichardSmedley** [comment]
> I think there should be a comma after the `}` on line 42

Ooh, good spot - I was too busy looking at the API within the {}.
These things need many eyes! :)

**Comment by jamesnocentini** [comment]
@RichardSmedley @simon-dew thanks

**Pull request merged**
