### PR TITLE
switch to using AsciiDoc macros to insert Swagger / JSON config UI components (master)

### PR DESCRIPTION
**Pull request by mojavelinux**
You can find the source for these macros here:

https://github.com/couchbase/docs-site/tree/master/lib

### CODE REVIEW

**Comment by jamiltz** [comment]
OK. I've tried to build it and see the following output:

image

Antora config:

```bash
site:
  title: Couchbase Documentation
content:
  sources:
  - url: couchbase-lite
    branches: [master, release/2.0, opendevise-relative-links-release/1.4]
  - url: sync-gateway-docs
    branches: [opendevise-swagger-macros-master, release/1.5]
asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v113/ui-bundle.zip
```

**Comment by jamiltz** [comment]
Also, this link https://github.com/couchbase/docs-site/tree/master/lib 404s for me. Might be a private repo I don't have access to.

**Comment by mojavelinux** [comment]
Your second comment explains the problem from the first ;)

The docs-site repository provides the source of the Asciidoctor extension that replaces the swagger_ui macro with the HTML to load the Swagger UI. For now, I'll just send them to you until the permissions are sorted out.

Here's how they are loaded in the playbook file:

```yml
asciidoc:
  extensions:
  - ./lib/block-json-config-ui-macro.js
  - ./lib/block-swagger-ui-macro.js
```

**Comment by jamiltz** [comment]
Ah ok, now I understand how it works. Looks great!

**Comment by mojavelinux** [comment]
\o/

**Pull request merged**
