### PR TITLE
DOC-4725

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-4725

### CODE REVIEW

**Comment by jamesnocentini** [comment]
@adamcfraser do you recall in which version of SG the config's `feed_type` default value was changed from `TAP` to `DCP`?

**Comment by jamesnocentini** [comment]
^^^ this PR needs a review when able (@bbrks or @adamcfraser )

**Comment by adamcfraser** [comment]
PR looks good, default feed type was changed to DCP in 1.5.0.

**Comment by jamesnocentini** [comment]
> PR looks good, default feed type was changed to DCP in 1.5.0.

@adamcfraser ok thanks!

**Pull request merged**
